name: Organization Discord Notify

on:
  workflow_call:
    inputs:
      # Required inputs
      status:
        description: "Job status (success, failure, cancelled)"
        required: true
        type: string
      workflow:
        description: "Workflow name"
        required: true
        type: string
      job:
        description: "Job name"
        required: true
        type: string
      
      # Optional customization
      custom_title:
        description: "Custom title (optional)"
        required: false
        type: string
        default: ""
      custom_description:
        description: "Custom description (optional)"
        required: false
        type: string
        default: ""
      custom_username:
        description: "Custom username (optional)"
        required: false
        type: string
        default: "Devlander CI/CD"
      custom_avatar:
        description: "Custom avatar URL (optional)"
        required: false
        type: string
        default: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
      
      # Advanced options
      include_commit_message:
        description: "Include commit message"
        required: false
        type: string
        default: "true"
      include_duration:
        description: "Include duration"
        required: false
        type: string
        default: "true"
      include_changed_files:
        description: "Include changed files"
        required: false
        type: string
        default: "false"
      include_environment:
        description: "Include environment info"
        required: false
        type: string
        default: "false"
      
      # Enterprise features
      thread_id:
        description: "Discord thread ID to send to"
        required: false
        type: string
        default: ""
      mention_users:
        description: "Comma-separated user IDs to mention"
        required: false
        type: string
        default: ""
      mention_roles:
        description: "Comma-separated role IDs to mention"
        required: false
        type: string
        default: ""
      
      # Smart features
      auto_detect:
        description: "Auto-detect workflow context"
        required: false
        type: string
        default: "true"
      smart_formatting:
        description: "Use smart formatting with emojis"
        required: false
        type: string
        default: "true"
      use_rich_embeds:
        description: "Use rich embeds with fields"
        required: false
        type: string
        default: "true"
      compact_mode:
        description: "Use compact mode for shorter notifications"
        required: false
        type: string
        default: "false"
      
      # Colors
      color_success:
        description: "Success color (hex without #)"
        required: false
        type: string
        default: "00ff00"
      color_failure:
        description: "Failure color (hex without #)"
        required: false
        type: string
        default: "ff0000"
      color_cancelled:
        description: "Cancelled color (hex without #)"
        required: false
        type: string
        default: "808080"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Devlander-Software/discord-webhook-notifier-action@v1
        with:
          # Use organization secret
          webhook: ${{ secrets.ORG_DISCORD_WEBHOOK_URL }}
          
          # Required fields
          status: ${{ inputs.status }}
          workflow: ${{ inputs.workflow }}
          job: ${{ inputs.job }}
          repo: ${{ github.repository }}
          branch: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          actor: ${{ github.actor }}
          run_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
          # Custom options
          title: ${{ inputs.custom_title }}
          description: ${{ inputs.custom_description }}
          username: ${{ inputs.custom_username }}
          avatar_url: ${{ inputs.custom_avatar }}
          
          # Advanced options
          include_commit_message: ${{ inputs.include_commit_message }}
          include_duration: ${{ inputs.include_duration }}
          include_changed_files: ${{ inputs.include_changed_files }}
          include_environment: ${{ inputs.include_environment }}
          
          # Enterprise features
          thread_id: ${{ inputs.thread_id }}
          mention_users: ${{ inputs.mention_users }}
          mention_roles: ${{ inputs.mention_roles }}
          
          # Smart features
          auto_detect: ${{ inputs.auto_detect }}
          smart_formatting: ${{ inputs.smart_formatting }}
          use_rich_embeds: ${{ inputs.use_rich_embeds }}
          compact_mode: ${{ inputs.compact_mode }}
          
          # Colors
          color_success: ${{ inputs.color_success }}
          color_failure: ${{ inputs.color_failure }}
          color_cancelled: ${{ inputs.color_cancelled }} 