name: CI/CD with Discord Notifications

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: npm test
      - name: Notify Discord
        uses: Devlander-Software/discord-notify-action/.github/workflows/org-discord-notify.yml@production
        if: always()
        with:
          status: ${{ job.status }}
          workflow: ${{ github.workflow }}
          job: ${{ github.job }}

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: npm run build
      - name: Notify Discord
        uses: Devlander-Software/discord-notify-action/.github/workflows/org-discord-notify.yml@production
        if: always()
        with:
          status: ${{ job.status }}
          workflow: ${{ github.workflow }}
          job: ${{ github.job }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: npm run deploy
      - name: Notify Discord
        uses: Devlander-Software/discord-notify-action/.github/workflows/org-discord-notify.yml@production
        if: always()
        with:
          status: ${{ job.status }}
          workflow: ${{ github.workflow }}
          job: ${{ github.job }}
          custom_title: "🚀 Deployment Status"
          custom_username: "Deployment Bot" 