title: Discord Webhook Notifier Action
description: The most advanced Discord webhook notification action for GitHub Actions
url: "https://devlander.github.io"
baseurl: "/discord-webhook-notifier-action"

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/devlander-software/discord-webhook-notifier-action

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include
include:
  - _pages

# SEO
author:
  name: Devlander Software
  email: support@devlander.com
  bio: Building the most advanced Discord notification action for GitHub Actions
  location: GitHub
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/devlander"

# Social
social:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/devlander-software/discord-webhook-notifier-action"
  - label: "Issues"
    icon: "fas fa-fw fa-bug"
    url: "https://github.com/devlander-software/discord-webhook-notifier-action/issues"
  - label: "Discussions"
    icon: "fas fa-fw fa-comments"
    url: "https://github.com/devlander-software/discord-webhook-notifier-action/discussions"

# Navigation
header_pages:
  - README.md
  - installation.md
  - configuration.md
  - examples.md
  - guides/organization-setup.md
  - guides/testing.md
  - reference/comparison.md
  - contributing.md
  - security.md

# Footer
footer:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/devlander-software/discord-webhook-notifier-action"
  - label: "Issues"
    icon: "fas fa-fw fa-bug"
    url: "https://github.com/devlander-software/discord-webhook-notifier-action/issues"
  - label: "Discussions"
    icon: "fas fa-fw fa-comments"
    url: "https://github.com/devlander-software/discord-webhook-notifier-action/discussions"
  - label: "License"
    icon: "fas fa-fw fa-file-alt"
    url: "https://github.com/devlander-software/discord-webhook-notifier-action/blob/production/LICENSE" 