name: Release Action

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## What's Changed
            
            This release includes:
            - Enhanced Discord notification features
            - Improved error handling and retry logic
            - Better documentation and examples
            - Organization-wide notification support
            
            ## Installation
            
            ```yaml
            - name: Discord Notification
              uses: devlander/discord-webhook-notifier-action@v1
              with:
                webhook: ${{ secrets.DISCORD_WEBHOOK }}
                status: ${{ job.status }}
                workflow: ${{ github.workflow }}
                job: ${{ github.job }}
                repo: ${{ github.repository }}
                branch: ${{ github.ref_name }}
                commit: ${{ github.sha }}
                actor: ${{ github.actor }}
                run_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ```
            
            ## Documentation
            
            - [Installation Guide](https://devlander-software.github.io/discord-webhook-notifier-action/installation.html)
            - [Configuration Options](https://devlander-software.github.io/discord-webhook-notifier-action/configuration.html)
            - [Examples](https://devlander-software.github.io/discord-webhook-notifier-action/examples.html)
            
            ## Support
            
            - [Issues](https://github.com/devlander/discord-webhook-notifier-action/issues)
            - [Discussions](https://github.com/devlander/discord-webhook-notifier-action/discussions)
          draft: false
          prerelease: false 