name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Simulate Success
        run: echo "Test successful"
        
      - name: Test Discord Notification (Success)
        uses: ./
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          workflow: ${{ github.workflow }}
          job: ${{ github.job }}
          repo: ${{ github.repository }}
          branch: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          actor: ${{ github.actor }}
          run_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  test-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Simulate Failure
        run: exit 1
        
      - name: Test Discord Notification (Failure)
        uses: ./
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          workflow: ${{ github.workflow }}
          job: ${{ github.job }}
          repo: ${{ github.repository }}
          branch: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          actor: ${{ github.actor }}
          run_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  test-customization:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Simulate Success
        run: echo "Customization test successful"
        
      - name: Test Custom Discord Notification
        uses: ./
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          workflow: ${{ github.workflow }}
          job: ${{ github.job }}
          repo: ${{ github.repository }}
          branch: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          actor: ${{ github.actor }}
          run_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          # Test customization options
          title: "🚀 Custom Test Notification"
          description: "This is a **custom description** with **markdown** formatting!\n\nTesting the customization features of the Discord Webhook Notifier Action."
          username: "Custom Test Bot"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          include_commit_message: "true"
          include_duration: "true"
          color_success: "00ff00"
          color_failure: "ff0000"
          color_cancelled: "808080" 